INSERT INTO EMPLOYEE (ID, ACTIVE, APELLIDO, LASTNAME, NAME) VALUES (5, TRUE, 'Lopez1', 'Gomez', 'Ana');
INSERT INTO EMPLOYEE (ID, ACTIVE, APELLIDO, LASTNAME, NAME) VALUES (6, TRUE, 'Lopez2', 'Gomez', 'Mayra');
INSERT INTO EMPLOYEE (ID, ACTIVE, APELLIDO, LASTNAME, NAME) VALUES (7, TRUE, 'Lopez3', 'Gomez', 'Manuel');
INSERT INTO EMPLOYEE (ID, ACTIVE, APELLIDO, LASTNAME, NAME) VALUES (8, TRUE, 'Yanez', 'Gozalez', 'Cesar');

INSERT INTO EMPLOYEE (ID, ACTIVE, APELLIDO, LASTNAME, NAME) VALUES (9, TRUE, 'TREJO', 'GOMEZ', 'TANIA');
